plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "gapl"

/* ANTLR project (.g4)
 *    ⬇ generates
 * GeneratedParser (Kotlin code)
 *    ⬇ used by
 * Compiler (custom Kotlin logic to convert parsed gapl into verilog)
 *    ⬇ outputs
 * Verilog (.v files, including the source generated by the compiler and the test harness)
 *    ⬇ compiled by
 * Vivado project (synthesis/simulation)
 */

include(
    "antlr",
    "compiler",
    "simtest",
    "basys",
    "netfpga",
)