plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "gapl"

/* ANTLR project (.g4)
 *    ⬇ generates
 * GeneratedParser (Kotlin code)
 *    ⬇ used by
 * Analyzer (parses/resolves gapl into a semantic AST + diagnostics)
 *    ⬇ used by
 * Compiler (custom Kotlin logic to convert the AST into verilog)
 *    ⬇ outputs
 * Verilog (.v files, including the source generated by the compiler and the test harness)
 *    ⬇ compiled by
 * Vivado project (synthesis/simulation)
 */

include(
    "antlr", // Parser / Lexer
    "analyzer", // Use generated parser to build a semantic AST + diagnostics
    "compiler", // Use analyzer to build gapl compiler
    "lsp", // Language server wrapping analyzer for editor integrations
    "simtest",
    "gapl-example", // Use compiler to convert this gapl code into verilog
    "basys", // Use generated verilog, along with a test harness, to test design on Basys 3
    "netfpga", // Use generated verilog, along with a test harness, to test design on NetFPGA
    "netfpga:hw-test",
    "latency-finder"
)