//
// Copyright (c) 2019 Yuta Tokusashi
// All rights reserved.
//
//
//  File:
//        db_regs_defines.h
//
//  Description:
//        This file is automatically generated with header defines for the software
//
// This software was developed by
// Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//

// Registers offset definitions

#define SUME_DB_ID_0_OFFSET 0x0
#define SUME_DB_ID_0_DEFAULT 0x0000DB00
#define SUME_DB_ID_0_WIDTH 32
#define SUME_DB_VERSION_0_OFFSET 0x4
#define SUME_DB_VERSION_0_DEFAULT 0x1
#define SUME_DB_VERSION_0_WIDTH 32
#define SUME_DB_RESET_0_OFFSET 0x8
#define SUME_DB_RESET_0_DEFAULT 0x0
#define SUME_DB_RESET_0_WIDTH 16
#define SUME_DB_FLIP_0_OFFSET 0xC
#define SUME_DB_FLIP_0_DEFAULT 0x0
#define SUME_DB_FLIP_0_WIDTH 32
#define SUME_DB_DEBUG_0_OFFSET 0x10
#define SUME_DB_DEBUG_0_DEFAULT 0x0
#define SUME_DB_DEBUG_0_WIDTH 32
#define SUME_DB_PKTIN_0_OFFSET 0x14
#define SUME_DB_PKTIN_0_DEFAULT 0x0
#define SUME_DB_PKTIN_0_WIDTH 32
#define SUME_DB_PKTOUT_0_OFFSET 0x18
#define SUME_DB_PKTOUT_0_DEFAULT 0x0
#define SUME_DB_PKTOUT_0_WIDTH 32
#define SUME_DB_P0PKTIN_0_OFFSET 0x1C
#define SUME_DB_P0PKTIN_0_DEFAULT 0x0
#define SUME_DB_P0PKTIN_0_WIDTH 32
#define SUME_DB_P0PKTOUT_0_OFFSET 0x20
#define SUME_DB_P0PKTOUT_0_DEFAULT 0x0
#define SUME_DB_P0PKTOUT_0_WIDTH 32
#define SUME_DB_P1PKTIN_0_OFFSET 0x24
#define SUME_DB_P1PKTIN_0_DEFAULT 0x0
#define SUME_DB_P1PKTIN_0_WIDTH 32
#define SUME_DB_P1PKTOUT_0_OFFSET 0x28
#define SUME_DB_P1PKTOUT_0_DEFAULT 0x0
#define SUME_DB_P1PKTOUT_0_WIDTH 32
#define SUME_DB_P2PKTIN_0_OFFSET 0x2C
#define SUME_DB_P2PKTIN_0_DEFAULT 0x0
#define SUME_DB_P2PKTIN_0_WIDTH 32
#define SUME_DB_P2PKTOUT_0_OFFSET 0x30
#define SUME_DB_P2PKTOUT_0_DEFAULT 0x0
#define SUME_DB_P2PKTOUT_0_WIDTH 32
#define SUME_DB_P0DEBUG_0_OFFSET 0x34
#define SUME_DB_P0DEBUG_0_DEFAULT 0x0
#define SUME_DB_P0DEBUG_0_WIDTH 8
#define SUME_DB_P1DEBUG_0_OFFSET 0x38
#define SUME_DB_P1DEBUG_0_DEFAULT 0x0
#define SUME_DB_P1DEBUG_0_WIDTH 8
#define SUME_DB_P2DEBUG_0_OFFSET 0x3C
#define SUME_DB_P2DEBUG_0_DEFAULT 0x0
#define SUME_DB_IPADDR_0_OFFSET 0x40
#define SUME_DB_IPADDR_0_DEFAULT 0x0
#define SUME_DB_IPADDR_0_WIDTH 32
#define SUME_DB_KVSPORT_0_OFFSET 0x44
#define SUME_DB_KVSPORT_0_DEFAULT 0x2BCB
#define SUME_DB_KVSPORT_0_WIDTH 16
#define SUME_DB_MODE_0_OFFSET 0x48
#define SUME_DB_MODE_0_DEFAULT 0x1
#define SUME_DB_MODE_0_WIDTH 8
#define SUME_DB_DEBUG0_0_OFFSET 0x4C
#define SUME_DB_DEBUG0_0_DEFAULT 0x0
#define SUME_DB_DEBUG0_0_WIDTH 32
#define SUME_DB_DEBUG1_0_OFFSET 0x50
#define SUME_DB_DEBUG1_0_DEFAULT 0x0
#define SUME_DB_DEBUG1_0_WIDTH 32
#define SUME_DB_L1HIT_0_OFFSET 0x54
#define SUME_DB_L1HIT_0_DEFAULT 0x0
#define SUME_DB_L1HIT_0_WIDTH 32
#define SUME_DB_L1MISS_0_OFFSET 0x58
#define SUME_DB_L1MISS_0_DEFAULT 0x0
#define SUME_DB_L1MISS_0_WIDTH 32
#define SUME_DB_DRAM_0_OFFSET 0x5C
#define SUME_DB_DRAM_0_DEFAULT 0x0
#define SUME_DB_DRAM_0_WIDTH 32
#define SUME_DB_DRAMIN_0_OFFSET 0x60
#define SUME_DB_DRAMIN_0_DEFAULT 0x0
#define SUME_DB_DRAMIN_0_WIDTH 32
#define SUME_DB_DRAMOUT_0_OFFSET 0x64
#define SUME_DB_DRAMOUT_0_DEFAULT 0x0
#define SUME_DB_DRAMOUT_0_WIDTH 32
#define SUME_DB_SRAM0WR_0_OFFSET 0x68
#define SUME_DB_SRAM0WR_0_DEFAULT 0x0
#define SUME_DB_SRAM0WR_0_WIDTH 32
#define SUME_DB_SRAM0RD_0_OFFSET 0x6C
#define SUME_DB_SRAM0RD_0_DEFAULT 0x0
#define SUME_DB_SRAM0RD_0_WIDTH 32
#define SUME_DB_SRAM1WR_0_OFFSET 0x70
#define SUME_DB_SRAM1WR_0_DEFAULT 0x0
#define SUME_DB_SRAM1WR_0_WIDTH 32
#define SUME_DB_SRAM1RD_0_OFFSET 0x74
#define SUME_DB_SRAM1RD_0_DEFAULT 0x0
#define SUME_DB_SRAM1RD_0_WIDTH 32
#define SUME_DB_P0CHUNK_0_OFFSET 0x78
#define SUME_DB_P0CHUNK_0_DEFAULT 0x0
#define SUME_DB_P0CHUNK_0_WIDTH 32
#define SUME_DB_P1CHUNK_0_OFFSET 0x7C
#define SUME_DB_P1CHUNK_0_DEFAULT 0x0
#define SUME_DB_P1CHUNK_0_WIDTH 32
#define SUME_DB_P2CHUNK_0_OFFSET 0x80
#define SUME_DB_P2CHUNK_0_DEFAULT 0x0
#define SUME_DB_P2CHUNK_0_WIDTH 32
#define SUME_DB_P0ERR_0_OFFSET 0x84
#define SUME_DB_P0ERR_0_DEFAULT 0x0
#define SUME_DB_P0ERR_0_WIDTH 32
#define SUME_DB_P1ERR_0_OFFSET 0x88
#define SUME_DB_P1ERR_0_DEFAULT 0x0
#define SUME_DB_P1ERR_0_WIDTH 32
#define SUME_DB_P2ERR_0_OFFSET 0x8C
#define SUME_DB_P2ERR_0_DEFAULT 0x0
#define SUME_DB_P2ERR_0_WIDTH 32
#define SUME_DB_DRAMRD_0_OFFSET 0x90
#define SUME_DB_DRAMRD_0_DEFAULT 0x0
#define SUME_DB_DRAMRD_0_WIDTH 32
#define SUME_DB_SRAMIN_0_OFFSET 0x94
#define SUME_DB_SRAMIN_0_DEFAULT 0x0
#define SUME_DB_SRAMIN_0_WIDTH 32
#define SUME_DB_SRAMOUT_0_OFFSET 0x98
#define SUME_DB_SRAMOUT_0_DEFAULT 0x0
#define SUME_DB_SRAMOUT_0_WIDTH 32
#define SUME_DB_LUTIN_0_OFFSET 0x9C
#define SUME_DB_LUTIN_0_DEFAULT 0x0
#define SUME_DB_LUTIN_0_WIDTH 32
#define SUME_DB_LUTOUT_0_OFFSET 0x100
#define SUME_DB_LUTOUT_0_DEFAULT 0x0
#define SUME_DB_LUTOUT_0_WIDTH 32
#define SUME_DB_PEEN_0_OFFSET 0x104
#define SUME_DB_PEEN_0_DEFAULT 0x1
#define SUME_DB_PEEN_0_WIDTH 16
