//
// Copyright (c) 2015 University of Cambridge
// Modified by Yuta Tokusashi
// All rights reserved.
//
//
//  File:
//        output_port_lookup_cpu_regs_defines.v
//
//  Module:
//        output_port_lookup_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by
// Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


           `define  REG_ID_BITS					31:0
           `define  REG_ID_WIDTH				32
           `define  REG_ID_DEFAULT				32'h0000DB00
           `define  REG_ID_ADDR					32'h0

           `define  REG_VERSION_BITS			31:0
           `define  REG_VERSION_WIDTH			32
           `define  REG_VERSION_DEFAULT			32'h1
           `define  REG_VERSION_ADDR			32'h4

           `define  REG_RESET_BITS				15:0
           `define  REG_RESET_WIDTH				16
           `define  REG_RESET_DEFAULT			16'h0
           `define  REG_RESET_ADDR				32'h8

           `define  REG_FLIP_BITS				31:0
           `define  REG_FLIP_WIDTH				32
           `define  REG_FLIP_DEFAULT			32'h0
           `define  REG_FLIP_ADDR				32'hC

           `define  REG_DEBUG_BITS				31:0
           `define  REG_DEBUG_WIDTH				32
           `define  REG_DEBUG_DEFAULT			32'h0
           `define  REG_DEBUG_ADDR				32'h10

           `define  REG_PKTIN_BITS				31:0
           `define  REG_PKTIN_WIDTH				32
           `define  REG_PKTIN_DEFAULT			32'h0
           `define  REG_PKTIN_ADDR				32'h14

           `define  REG_PKTOUT_BITS				31:0
           `define  REG_PKTOUT_WIDTH			32
           `define  REG_PKTOUT_DEFAULT			32'h0
           `define  REG_PKTOUT_ADDR				32'h18

           `define  REG_P0PKTIN_BITS				31:0
           `define  REG_P0PKTIN_WIDTH				32
           `define  REG_P0PKTIN_DEFAULT			32'h0
           `define  REG_P0PKTIN_ADDR				32'h1C

           `define  REG_P0PKTOUT_BITS				31:0
           `define  REG_P0PKTOUT_WIDTH			32
           `define  REG_P0PKTOUT_DEFAULT			32'h0
           `define  REG_P0PKTOUT_ADDR				32'h20

           `define  REG_P1PKTIN_BITS				31:0
           `define  REG_P1PKTIN_WIDTH				32
           `define  REG_P1PKTIN_DEFAULT			32'h0
           `define  REG_P1PKTIN_ADDR				32'h24

           `define  REG_P1PKTOUT_BITS				31:0
           `define  REG_P1PKTOUT_WIDTH			32
           `define  REG_P1PKTOUT_DEFAULT			32'h0
           `define  REG_P1PKTOUT_ADDR				32'h28

           `define  REG_P2PKTIN_BITS				31:0
           `define  REG_P2PKTIN_WIDTH				32
           `define  REG_P2PKTIN_DEFAULT			32'h0
           `define  REG_P2PKTIN_ADDR				32'h2C

           `define  REG_P2PKTOUT_BITS				31:0
           `define  REG_P2PKTOUT_WIDTH			32
           `define  REG_P2PKTOUT_DEFAULT			32'h0
           `define  REG_P2PKTOUT_ADDR				32'h30

           `define  REG_P0DEBUG_BITS				31:0
           `define  REG_P0DEBUG_WIDTH			32
           `define  REG_P0DEBUG_DEFAULT				32'h0
           `define  REG_P0DEBUG_ADDR				32'h34

           `define  REG_P1DEBUG_BITS				31:0
           `define  REG_P1DEBUG_WIDTH			32
           `define  REG_P1DEBUG_DEFAULT			32'h0
           `define  REG_P1DEBUG_ADDR				32'h38

           `define  REG_P2DEBUG_BITS				31:0
           `define  REG_P2DEBUG_WIDTH			32
           `define  REG_P2DEBUG_DEFAULT			32'h0
           `define  REG_P2DEBUG_ADDR				32'h3C

           `define  REG_IPADDR_BITS				31:0
           `define  REG_IPADDR_WIDTH			32
           `define  REG_IPADDR_DEFAULT			32'h0
           `define  REG_IPADDR_ADDR				32'h40

           `define  REG_KVSPORT_BITS			15:0
           `define  REG_KVSPORT_WIDTH			16	
           `define  REG_KVSPORT_DEFAULT			16'd11211
           `define  REG_KVSPORT_ADDR			32'h44

           `define  REG_MODE_BITS			7:0
           `define  REG_MODE_WIDTH			8	
           `define  REG_MODE_DEFAULT			8'b0000_0001
           `define  REG_MODE_ADDR			32'h48

           `define  REG_DEBUG0_BITS			31:0
           `define  REG_DEBUG0_WIDTH			32	
           `define  REG_DEBUG0_DEFAULT			32'd0
           `define  REG_DEBUG0_ADDR			32'h4C

           `define  REG_DEBUG1_BITS			31:0
           `define  REG_DEBUG1_WIDTH			32	
           `define  REG_DEBUG1_DEFAULT			32'd0
           `define  REG_DEBUG1_ADDR			32'h50

           `define  REG_L1HIT_BITS				31:0
           `define  REG_L1HIT_WIDTH				32	
           `define  REG_L1HIT_DEFAULT			32'h0
           `define  REG_L1HIT_ADDR				32'h54
			
           `define  REG_L1MISS_BITS				31:0
           `define  REG_L1MISS_WIDTH			32	
           `define  REG_L1MISS_DEFAULT			32'h0
           `define  REG_L1MISS_ADDR				32'h58

           `define  REG_DRAM_BITS				31:0
           `define  REG_DRAM_WIDTH			32	
           `define  REG_DRAM_DEFAULT			32'h0
           `define  REG_DRAM_ADDR				32'h5C

           `define  REG_DRAMIN_BITS				31:0
           `define  REG_DRAMIN_WIDTH			32	
           `define  REG_DRAMIN_DEFAULT			32'h0
           `define  REG_DRAMIN_ADDR				32'h60

           `define  REG_DRAMOUT_BITS				31:0
           `define  REG_DRAMOUT_WIDTH			32	
           `define  REG_DRAMOUT_DEFAULT			32'h0
           `define  REG_DRAMOUT_ADDR				32'h64

           `define  REG_SRAM0WR_BITS				31:0
           `define  REG_SRAM0WR_WIDTH			32	
           `define  REG_SRAM0WR_DEFAULT			32'h0
           `define  REG_SRAM0WR_ADDR				32'h68

           `define  REG_SRAM0RD_BITS				31:0
           `define  REG_SRAM0RD_WIDTH			32	
           `define  REG_SRAM0RD_DEFAULT			32'h0
           `define  REG_SRAM0RD_ADDR				32'h6C

           `define  REG_SRAM1WR_BITS				31:0
           `define  REG_SRAM1WR_WIDTH			32	
           `define  REG_SRAM1WR_DEFAULT			32'h0
           `define  REG_SRAM1WR_ADDR				32'h70

           `define  REG_SRAM1RD_BITS				31:0
           `define  REG_SRAM1RD_WIDTH			32	
           `define  REG_SRAM1RD_DEFAULT			32'h0
           `define  REG_SRAM1RD_ADDR				32'h74

           `define  REG_P0CHUNK_BITS				31:0
           `define  REG_P0CHUNK_WIDTH			32
           `define  REG_P0CHUNK_DEFAULT			32'h0
           `define  REG_P0CHUNK_ADDR				32'h78

           `define  REG_P1CHUNK_BITS				31:0
           `define  REG_P1CHUNK_WIDTH			32
           `define  REG_P1CHUNK_DEFAULT			32'h0
           `define  REG_P1CHUNK_ADDR				32'h7C

           `define  REG_P2CHUNK_BITS				31:0
           `define  REG_P2CHUNK_WIDTH			32
           `define  REG_P2CHUNK_DEFAULT			32'h0
           `define  REG_P2CHUNK_ADDR				32'h80

           `define  REG_P0ERR_BITS				31:0
           `define  REG_P0ERR_WIDTH			32
           `define  REG_P0ERR_DEFAULT			32'h0
           `define  REG_P0ERR_ADDR				32'h84

           `define  REG_P1ERR_BITS				31:0
           `define  REG_P1ERR_WIDTH			32
           `define  REG_P1ERR_DEFAULT			32'h0
           `define  REG_P1ERR_ADDR				32'h88

           `define  REG_P2ERR_BITS				31:0
           `define  REG_P2ERR_WIDTH			32
           `define  REG_P2ERR_DEFAULT			32'h0
           `define  REG_P2ERR_ADDR				32'h8C

           `define  REG_DRAMRD_BITS				31:0
           `define  REG_DRAMRD_WIDTH			32
           `define  REG_DRAMRD_DEFAULT			32'h0
           `define  REG_DRAMRD_ADDR				32'h90

           `define  REG_SRAMIN_BITS				31:0
           `define  REG_SRAMIN_WIDTH			32
           `define  REG_SRAMIN_DEFAULT			32'h0
           `define  REG_SRAMIN_ADDR				32'h94

           `define  REG_SRAMOUT_BITS				31:0
           `define  REG_SRAMOUT_WIDTH			32
           `define  REG_SRAMOUT_DEFAULT			32'h0
           `define  REG_SRAMOUT_ADDR				32'h98

           `define  REG_LUTIN_BITS				31:0
           `define  REG_LUTIN_WIDTH			32
           `define  REG_LUTIN_DEFAULT			32'h0
           `define  REG_LUTIN_ADDR				32'h9C

           `define  REG_LUTOUT_BITS				31:0
           `define  REG_LUTOUT_WIDTH			32
           `define  REG_LUTOUT_DEFAULT			32'h0
           `define  REG_LUTOUT_ADDR				32'h100

           `define  REG_PEEN_BITS				15:0
           `define  REG_PEEN_WIDTH			16
           `define  REG_PEEN_DEFAULT			16'h1f
           `define  REG_PEEN_ADDR				16'h104

           `define  REG_P3PKTIN_BITS				31:0
           `define  REG_P3PKTIN_WIDTH				32
           `define  REG_P3PKTIN_DEFAULT			32'h0
           `define  REG_P3PKTIN_ADDR				32'h108

           `define  REG_P3PKTOUT_BITS				31:0
           `define  REG_P3PKTOUT_WIDTH			32
           `define  REG_P3PKTOUT_DEFAULT			32'h0
           `define  REG_P3PKTOUT_ADDR				32'h10C

           `define  REG_P4PKTIN_BITS				31:0
           `define  REG_P4PKTIN_WIDTH				32
           `define  REG_P4PKTIN_DEFAULT			32'h0
           `define  REG_P4PKTIN_ADDR				32'h110

           `define  REG_P4PKTOUT_BITS				31:0
           `define  REG_P4PKTOUT_WIDTH			32
           `define  REG_P4PKTOUT_DEFAULT			32'h0
           `define  REG_P4PKTOUT_ADDR				32'h114

           `define  REG_SCACHEEN_BITS				7:0
           `define  REG_SCACHEEN_WIDTH			8
           `define  REG_SCACHEEN_DEFAULT			8'h1
           `define  REG_SCACHEEN_ADDR				32'h130

           `define  REG_CLOCKGATE_BITS				7:0
           `define  REG_CLOCKGATE_WIDTH			8
           `define  REG_CLOCKGATE_DEFAULT			8'h0
           `define  REG_CLOCKGATE_ADDR				32'h134

           `define  REG_DRAMCACHEALL_BITS			31:0
           `define  REG_DRAMCACHEALL_WIDTH			32
           `define  REG_DRAMCACHEALL_DEFAULT		32'h0
           `define  REG_DRAMCACHEALL_ADDR			32'h138

           `define  REG_DRAMCACHEHIT_BITS			31:0
           `define  REG_DRAMCACHEHIT_WIDTH			32
           `define  REG_DRAMCACHEHIT_DEFAULT		32'h0
           `define  REG_DRAMCACHEHIT_ADDR			32'h13C

           `define  REG_STATS_BITS					31:0
           `define  REG_STATS_WIDTH					32
           `define  REG_STATS_DEFAULT				32'h0
           `define  REG_STATS_ADDR					32'h140

           `define  REG_STATG_BITS					31:0
           `define  REG_STATG_WIDTH					32
           `define  REG_STATG_DEFAULT				32'h0
           `define  REG_STATG_ADDR					32'h144

           `define  REG_STATD_BITS					31:0
           `define  REG_STATD_WIDTH					32
           `define  REG_STATD_DEFAULT				32'h0
           `define  REG_STATD_ADDR					32'h148

           `define  REG_LAKEON_BITS					7:0
           `define  REG_LAKEON_WIDTH				8	
           `define  REG_LAKEON_DEFAULT				8'h7
           `define  REG_LAKEON_ADDR					32'h14C
//

//           `define  REG_P5PKTIN_BITS				31:0
//           `define  REG_P5PKTIN_WIDTH				32
//           `define  REG_P5PKTIN_DEFAULT			32'h0
//           `define  REG_P5PKTIN_ADDR				32'h118
//
//           `define  REG_P5PKTOUT_BITS				31:0
//           `define  REG_P5PKTOUT_WIDTH			32
//           `define  REG_P5PKTOUT_DEFAULT			32'h0
//           `define  REG_P5PKTOUT_ADDR				32'h11C
//
//           `define  REG_P6PKTIN_BITS				31:0
//           `define  REG_P6PKTIN_WIDTH				32
//           `define  REG_P6PKTIN_DEFAULT			32'h0
//           `define  REG_P6PKTIN_ADDR				32'h120
//
//           `define  REG_P6PKTOUT_BITS				31:0
//           `define  REG_P6PKTOUT_WIDTH			32
//           `define  REG_P6PKTOUT_DEFAULT			32'h0
//           `define  REG_P6PKTOUT_ADDR				32'h124
//
//           `define  REG_P7PKTIN_BITS				31:0
//           `define  REG_P7PKTIN_WIDTH				32
//           `define  REG_P7PKTIN_DEFAULT			32'h0
//           `define  REG_P7PKTIN_ADDR				32'h128
//
//           `define  REG_P7PKTOUT_BITS				31:0
//           `define  REG_P7PKTOUT_WIDTH			32
//           `define  REG_P7PKTOUT_DEFAULT			32'h0
//           `define  REG_P7PKTOUT_ADDR				32'h12C
//
//           `define  REG_P8PKTIN_BITS				31:0
//           `define  REG_P8PKTIN_WIDTH				32
//           `define  REG_P8PKTIN_DEFAULT			32'h0
//           `define  REG_P8PKTIN_ADDR				32'h130
//
//           `define  REG_P8PKTOUT_BITS				31:0
//           `define  REG_P8PKTOUT_WIDTH			32
//           `define  REG_P8PKTOUT_DEFAULT			32'h0
//           `define  REG_P8PKTOUT_ADDR				32'h134
//
//           `define  REG_P9PKTIN_BITS				31:0
//           `define  REG_P9PKTIN_WIDTH				32
//           `define  REG_P9PKTIN_DEFAULT			32'h0
//           `define  REG_P9PKTIN_ADDR				32'h138
//
//           `define  REG_P9PKTOUT_BITS				31:0
//           `define  REG_P9PKTOUT_WIDTH			32
//           `define  REG_P9PKTOUT_DEFAULT			32'h0
//           `define  REG_P9PKTOUT_ADDR				32'h13C
//
//           `define  REG_P10PKTIN_BITS				31:0
//           `define  REG_P10PKTIN_WIDTH				32
//           `define  REG_P10PKTIN_DEFAULT			32'h0
//           `define  REG_P10PKTIN_ADDR				32'h140
//
//           `define  REG_P10PKTOUT_BITS			31:0
//           `define  REG_P10PKTOUT_WIDTH			32
//           `define  REG_P10PKTOUT_DEFAULT			32'h0
//           `define  REG_P10PKTOUT_ADDR			32'h144
//
//           `define  REG_P11PKTIN_BITS				31:0
//           `define  REG_P11PKTIN_WIDTH				32
//           `define  REG_P11PKTIN_DEFAULT			32'h0
//           `define  REG_P11PKTIN_ADDR				32'h148
//
//           `define  REG_P11PKTOUT_BITS			31:0
//           `define  REG_P11PKTOUT_WIDTH			32
//           `define  REG_P11PKTOUT_DEFAULT			32'h0
//           `define  REG_P11PKTOUT_ADDR			32'h14C
//
//           `define  REG_P12PKTIN_BITS				31:0
//           `define  REG_P12PKTIN_WIDTH				32
//           `define  REG_P12PKTIN_DEFAULT			32'h0
//           `define  REG_P12PKTIN_ADDR				32'h150
//
//           `define  REG_P12PKTOUT_BITS			31:0
//           `define  REG_P12PKTOUT_WIDTH			32
//           `define  REG_P12PKTOUT_DEFAULT			32'h0
//           `define  REG_P12PKTOUT_ADDR			32'h154
//
//           `define  REG_P13PKTIN_BITS				31:0
//           `define  REG_P13PKTIN_WIDTH				32
//           `define  REG_P13PKTIN_DEFAULT			32'h0
//           `define  REG_P13PKTIN_ADDR				32'h158
//
//           `define  REG_P13PKTOUT_BITS			31:0
//           `define  REG_P13PKTOUT_WIDTH			32
//           `define  REG_P13PKTOUT_DEFAULT			32'h0
//           `define  REG_P13PKTOUT_ADDR			32'h15C
//
//           `define  REG_P14PKTIN_BITS				31:0
//           `define  REG_P14PKTIN_WIDTH			32
//           `define  REG_P14PKTIN_DEFAULT			32'h0
//           `define  REG_P14PKTIN_ADDR				32'h160
//
//           `define  REG_P14PKTOUT_BITS			31:0
//           `define  REG_P14PKTOUT_WIDTH			32
//           `define  REG_P14PKTOUT_DEFAULT			32'h0
//           `define  REG_P14PKTOUT_ADDR			32'h164
//
//           `define  REG_P15PKTIN_BITS				31:0
//           `define  REG_P15PKTIN_WIDTH			32
//           `define  REG_P15PKTIN_DEFAULT			32'h0
//           `define  REG_P15PKTIN_ADDR				32'h168
//
//           `define  REG_P15PKTOUT_BITS			31:0
//           `define  REG_P15PKTOUT_WIDTH			32
//           `define  REG_P15PKTOUT_DEFAULT			32'h0
//           `define  REG_P15PKTOUT_ADDR			32'h16C
//
