#
# Copyright (c) 2020 Marcin Wójcik
# All rights reserved.
#
# This software was developed by the University of Cambridge Computer
# Laboratory and supported by the UK's Engineering and Physical Sciences
# Research Council (EPSRC) under the EARL: sdn EnAbled MeasuRement for alL
# project (Project Reference EP/P025374/1).
#
# @NETFPGA_LICENSE_HEADER_START@
#
# Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
# license agreements. See the NOTICE file distributed with this work for
# additional information regarding copyright ownership. NetFPGA licenses this
# file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at:
#
#   http://www.netfpga-cic.org
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @NETFPGA_LICENSE_HEADER_END@
#

set design [lindex $argv 0]
set jobs   [lindex $argv 1]

open_project project/${design}.xpr

# GAPL: create_project.tcl's create_ip for gapl_kernel_ip only runs once, when hw/project doesn't
# yet exist (hw/Makefile's create_project target is skip-if-exists) - but the underlying packaged
# core (lib/hw/contrib/cores/gapl_kernel_v1_0_0/) gets regenerated by Gradle's
# packageCoreGaplKernel task every time the selected GAPL application changes. Without refreshing
# the project's own .xci here, switching applications on an already-created project would silently
# keep synthesizing whichever application was selected when the project was first created.
#
# Must be conditional, not unconditional: regenerating the .xci's output products touches their
# timestamps/content even when the underlying packaged core is unchanged, which made Vivado's own
# run-staleness tracking see the whole project as modified and cascade into a full resynthesis of
# every run (including the 30+ static control_sub sub-runs that have nothing to do with GAPL) -
# exactly the problem the reset_run removal above was meant to fix, reintroduced by this refresh.
# Only refresh when the packaged core's component.xml is actually newer than the project's
# existing .xci (i.e. packageCoreGaplKernel actually regenerated it since this .xci was made).
update_ip_catalog
if {[llength [get_ips gapl_kernel_ip -quiet]] > 0} {
    set gapl_kernel_component "$::env(SUME_FOLDER)/lib/hw/contrib/cores/gapl_kernel_v1_0_0/component.xml"
    set gapl_kernel_xci [get_property IP_FILE [get_ips gapl_kernel_ip]]
    if {[file mtime $gapl_kernel_component] > [file mtime $gapl_kernel_xci]} {
        puts "GAPL: gapl_kernel_ip's packaged core changed since this project's .xci was generated - refreshing"
        upgrade_ip [get_ips gapl_kernel_ip]
        reset_target all [get_ips gapl_kernel_ip]
        generate_target all [get_ips gapl_kernel_ip]
    } else {
        puts "GAPL: gapl_kernel_ip is already up to date with its packaged core - skipping refresh"
    }
}

# GAPL: no reset_run here - Vivado's own run staleness tracking (source/constraint/IP content
# hashes since the last successful synth_1) already makes launch_runs a fast no-op when nothing
# changed. Force-resetting unconditionally on every build was throwing that away.
launch_runs synth_1 -jobs ${jobs}
wait_on_run synth_1

exit