#
# GAPL: solves clk_wiz_ip's MMCM multiply/divide/jitter configuration for a requested clk_200
# period, using Vivado's own Clocking Wizard solver rather than hand-computed VCO/divide
# arithmetic - see the netfpga clock-period workflow investigation for why this exists: a past
# hand-edited config left the create_clock constraint and the physical MMCM disagreeing with each
# other, and separately, hand-computed jitter/phase-error numbers are specific to one exact
# multiply/divide combination and go stale silently if that combination ever changes without them
# being recomputed.
#
# Usage: vivado -mode batch -source solve_clk_wiz.tcl -tclargs <part> <primInFreqMHz>
#                <requestedPeriodNs> <outConfigTclPath> <outAchievedPeriodPath>
#
# Writes:
#   <outConfigTclPath>       - a ready-to-source Tcl snippet that configures clk_wiz_ip with the
#                               solved values (create_project.tcl sources this instead of embedding
#                               a hand-written -dict literal).
#   <outAchievedPeriodPath>  - the actual achieved clk_200 period in ns, as plain text. This - not
#                               the originally requested period - is what generateConstraints uses
#                               for the create_clock token, so the installed constraint can never
#                               disagree with what the MMCM actually produces.
#
# Fails loudly (non-zero exit, Vivado's own descriptive error) if the requested period isn't
# achievable by a single MMCM stage - see Vivado's own reported valid frequency range in that case.

set part                 [lindex $argv 0]
set prim_in_freq_mhz     [lindex $argv 1]
set requested_period_ns  [lindex $argv 2]
set out_config_tcl       [lindex $argv 3]
set out_achieved_period  [lindex $argv 4]

set requested_freq_mhz [expr {1000.0 / $requested_period_ns}]

create_project -in_memory -part $part

create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name clk_wiz_ip
set_property -dict [list \
  CONFIG.PRIM_IN_FREQ $prim_in_freq_mhz \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ $requested_freq_mhz \
  CONFIG.USE_SAFE_CLOCK_STARTUP {true} \
  CONFIG.RESET_TYPE {ACTIVE_LOW} \
  CONFIG.CLKIN1_JITTER_PS {50.0} \
  CONFIG.CLKOUT1_DRIVES {BUFGCE} \
  CONFIG.CLKOUT2_DRIVES {BUFGCE} \
  CONFIG.CLKOUT3_DRIVES {BUFGCE} \
  CONFIG.CLKOUT4_DRIVES {BUFGCE} \
  CONFIG.CLKOUT5_DRIVES {BUFGCE} \
  CONFIG.CLKOUT6_DRIVES {BUFGCE} \
  CONFIG.CLKOUT7_DRIVES {BUFGCE} \
  CONFIG.RESET_PORT {resetn} \
] [get_ips clk_wiz_ip]
# GAPL: deliberately does NOT set CONFIG.MMCM_CLKFBOUT_MULT_F/MMCM_CLKOUT0_DIVIDE_F - leaving
# those unset lets Vivado's own Clocking Wizard solve them from CLKOUT1_REQUESTED_OUT_FREQ, the
# same algorithm the GUI uses. Confirmed directly: this reproduces the same MULT_F/DIVIDE_F a
# hand-solved "VCO at its 600MHz floor, divide at its 128 ceiling" derivation gives for a period at
# the MMCM's minimum-frequency limit, and set_property fails with Vivado's own clear
# "Please enter valid freq in range (X - Y)" error (non-zero exit) if the request is infeasible -
# no separate feasibility check needed here, Vivado's own validation already provides one.

set ip [get_ips clk_wiz_ip]

set mult_f      [get_property CONFIG.MMCM_CLKFBOUT_MULT_F $ip]
set divide_f    [get_property CONFIG.MMCM_CLKOUT0_DIVIDE_F $ip]
set divclk_div  [get_property CONFIG.MMCM_DIVCLK_DIVIDE $ip]
set clkin_period [get_property CONFIG.MMCM_CLKIN1_PERIOD $ip]
set jitter      [get_property CONFIG.CLKOUT1_JITTER $ip]
set phase_error [get_property CONFIG.CLKOUT1_PHASE_ERROR $ip]

set achieved_freq_mhz [expr {double($prim_in_freq_mhz) * $mult_f / $divclk_div / $divide_f}]
set achieved_period_ns [expr {1000.0 / $achieved_freq_mhz}]

puts "GAPL: solved clk_wiz_ip for requested period ${requested_period_ns}ns (${requested_freq_mhz}MHz):"
puts "GAPL:   MULT_F=$mult_f DIVIDE_F=$divide_f DIVCLK_DIVIDE=$divclk_div"
puts "GAPL:   achieved period = ${achieved_period_ns}ns (${achieved_freq_mhz}MHz)"
puts "GAPL:   jitter=${jitter}ps phase_error=${phase_error}ps"

file mkdir [file dirname $out_config_tcl]
set fh [open $out_config_tcl w]
puts $fh "# GAPL: generated by solve_clk_wiz.tcl - do not hand-edit, edit clockPeriodNs instead."
puts $fh "# Solved for requested period ${requested_period_ns}ns; achieved ${achieved_period_ns}ns."
puts $fh "create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name clk_wiz_ip"
puts $fh "set_property -dict \[list \\"
puts $fh "  CONFIG.PRIM_IN_FREQ {$prim_in_freq_mhz} \\"
puts $fh "  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {$requested_freq_mhz} \\"
puts $fh "  CONFIG.USE_SAFE_CLOCK_STARTUP {true} \\"
puts $fh "  CONFIG.RESET_TYPE {ACTIVE_LOW} \\"
puts $fh "  CONFIG.CLKIN1_JITTER_PS {50.0} \\"
puts $fh "  CONFIG.CLKOUT1_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.CLKOUT2_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.CLKOUT3_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.CLKOUT4_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.CLKOUT5_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.CLKOUT6_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.CLKOUT7_DRIVES {BUFGCE} \\"
puts $fh "  CONFIG.MMCM_CLKFBOUT_MULT_F {$mult_f} \\"
puts $fh "  CONFIG.MMCM_CLKIN1_PERIOD {$clkin_period} \\"
puts $fh "  CONFIG.MMCM_CLKOUT0_DIVIDE_F {$divide_f} \\"
puts $fh "  CONFIG.MMCM_DIVCLK_DIVIDE {$divclk_div} \\"
puts $fh "  CONFIG.RESET_PORT {resetn} \\"
puts $fh "  CONFIG.CLKOUT1_JITTER {$jitter} \\"
puts $fh "  CONFIG.CLKOUT1_PHASE_ERROR {$phase_error} \\"
puts $fh "] \[get_ips clk_wiz_ip\]"
close $fh

file mkdir [file dirname $out_achieved_period]
set fh2 [open $out_achieved_period w]
puts -nonewline $fh2 [format "%.6f" $achieved_period_ns]
close $fh2

exit 0
